### ISSUE TITLE
NullPointerException and uPnP warning

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#16]
Got the following output (before successful discovery). This is no problem as this error is output to stderr and the camera results go to stdout, so I am able to read only what I need. Still I thought I should send you error data:

    Jul 30, 2015 11:57:24 PM net.sbbi.upnp.DiscoveryListener listenBroadCast 
    WARNING: Discovery message sender IP /192.168.0.6 does not match device description IP /169.254.4.117 skipping device, set the net.sbbi.upnp.ddos.matchip system property to false to avoid this check
    java.lang.NullPointerException
	at io.evercam.network.discovery.GatewayDevice.<init>(GatewayDevice.java:40)
	at io.evercam.network.NatRunnable.run(NatRunnable.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by liutingdu** [comment]
I'll fix the NullPointerException

But the warning message is from the UPnP library: https://github.com/RPTools/upnplib/blob/master/src/net/sbbi/upnp/DiscoveryListener.java

I'll try disable all logs from other libraries.

**Comment by scandox** [comment]
As I said those warnings are ok as they go to stderr

**Comment by liutingdu** [comment]
I fixed the exception and did some improvements around logging in my code. And I am keeping the logs in that library.

Thanks for reporting this, it's good for me to learn about logging :)
