### ISSUE TITLE
Image urls ought to be prefixed with https or with //

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#21]
Ideally on web pages we'd load all images and thumbnails with https. Discovery currently returns images prefixed with http. It seems to me there are a few options:

*    use a protocol relative prefix like //. Education: http://blog.wikimedia.org/2011/07/19/protocol-relative-urls-enabled-on-test-wikipedia-org/
*    always use https. Might break Android App or other systems?
*    we just replace the protocol when we use it in our webpages. This is easy but least correct.

@marcoherbst If this is an issue for Evercam core itself would appreciate knowledge.

**Comment by liutingdu** [comment]
The thumbnail URLs are returned from Evercam API - GET models/id

I'll close this one and move it to the API repository

https://github.com/evercam/evercam-api/issues/402
