### ISSUE TITLE
Discovery returning invalid ipv6 address

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#22]
It appears that during discovery sometimes an IPv6 Address is being returned. I guess the gateway can handle that (maybe), but the format the address is given is wrong. Sample data below:

    {
        "vendor_thumbnail_url": "",
        "mac_address": "00:00:00:00:00:00",
        "upnp_wan_http_port": null,
        "lan_rtsp_port": null,
        "model_id": "ds-2df7286-a",
        "wan_ip": "149.5.42.145",
        "upnp_wan_rtsp_port": null,
        "lan_http_port": 8090,
        "friendly_name": "",
        "vendor_id": "ds-2df7286-a",
        "lan_ip": "[fe80::4619:b7ff:fe1d:c6cf]",
        "model_thumbnail_url": ""
    }

This I can't really handle effectively. For now I'm discarding them.

@liutingdu I am sending you full data by email

**Comment by liutingdu** [comment]
The SOAP response from this camera is:

<d:ProbeMatches><d:ProbeMatch><wsadis:EndpointReference><wsadis:Address>urn:uuid:a7fc57d6-463d-11b4-82bf-4419b64968e1</wsadis:Address>
</wsadis:EndpointReference>
<d:Types>dn:NetworkVideoTransmitter tds:Device</d:Types>
<d:Scopes>onvif://www.onvif.org/type/video_encoder onvif://www.onvif.org/Profile/Streaming onvif://www.onvif.org/Profile/G onvif://www.onvif.org/hardware/DS-2CD2612F-I onvif://www.onvif.org/name/DS-2CD2612F-I onvif://www.onvif.org/location/city/hangzhou</d:Scopes>
<d:XAddrs>http://192.168.0.59:8059/onvif/device_service http://[fe80::4619:b6ff:fe49:68e1]:8059/onvif/device_service</d:XAddrs>
<d:MetadataVersion>10</d:MetadataVersion>
</d:ProbeMatch>

**Comment by scandox** [comment]
That strange IP address looks like a Link Local address - you should recall this from your studies of ZeroConf!
