### ISSUE TITLE
Runnable should return empty JSON cameras object if no cameras found

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#29]
At present the runnable discovery returns nothing at all if no cameras are discovered. Instead it should return:

     {"cameras": [ ] }

That way we know nothing went wrong. Just no cameras.

**Comment by liutingdu** [comment]
@scandox 

I just added the empty camera json array if no cameras are discovered.

But before the fix, if no cameras are discovered the behaviour should be print nothing with ```On normal completion: 0```.  You mentioned that you got ```On error: 1``` in the end, it means unexpected error/exception happened during discovery. 

So if you are seeing  ```On error: 1```, could you please send me the verbose log? It should contains the exception trace.
