### ISSUE TITLE
Runnable discovery jar file in Linux

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-discovery-java#3]

**Comment by liutingdu** [comment]
Added Main class: https://github.com/evercam/evercam-discovery-java/blob/master/src/io/evercam/network/Main.java

**Comment by marcoherbst** [comment]
Well done @liutingdu  ... I'm sure @scandox can't wait to use it.

**Comment by scandox** [comment]
I can't. So.excited

**Comment by liutingdu** [comment]
https://github.com/evercam/evercam-discovery-java/tree/master/release
