### ISSUE TITLE
how to get rtsp url of ip camera using onvif

### ISSUE THREAD

**Issue by alpeshprajapati89** [evercam/evercam-discovery-java#35]
I use ur library and i discover ip model and vendor name.
But rtsp url not getting please say how to get camera rtsp url.

**Comment by marcoherbst** [comment]
One way might be then to query this endpoint: 
https://media.evercam.io/v1/models/

**Comment by EpariNigam** [comment]
@marcoherbst Using that web service how to generate the RTSP URL?

**Comment by marcoherbst** [comment]
HI @EpariNigam  , to be honest, I'd suggest not bothering with this codebase. It's not being maintained. If you want the RTSP URL of a camera, ask the manufacturer or google the specific model.  Sorry I can't help.
