### ISSUE TITLE
Add command-line switches for runnable version (jar file)

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#7]
In order to make the runnable jar-file version work in a more ideal way and to adhere more closely to normal command-line behaviour of Linux utilities I suggest the following command-line switches:

*  -v, --verbose: without this switch there should be no logging output. At present the logging output of the program makes it very hard for another program to grab the output and parse it for cameras. If this switch is on, it helps with debugging, but if it is off, only the camera results should be output (empty [] if none).
*  -t, --terminate: with this switch, the process should terminate when it finishes. At the moment it simply hangs at the end of the run. This switch may not be needed at all, unless there is some useful reason that the program doesn't terminate.

**Comment by liutingdu** [comment]
@scandox 

When using --verbose, what format of output camera results is easy for you to use?(I was simply printing the toString() of the camera object at this moment)

And about --terminate, I agree that we don't need it, it will be done by adding exit codes in #8

**Comment by scandox** [comment]
Hi Liuting

Any structured format is ok but of.course JSON is probably the most ideal
FOR ME

**Comment by liutingdu** [comment]
Then I'll do JSON :+1:
