### ISSUE TITLE
Provide exit codes with the runnable jar file version

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#8]
The runnable jar-file version should provide system exit codes. At present it never terminates. However it should provide codes:

*  On normal completion: 0
*  On error: 1

You can provide more granular error exit codes if needed. But this would do for now.

**Comment by liutingdu** [comment]
Thanks for pointing this out!

**Comment by liutingdu** [comment]
@scandox 

When it's terminated, do you need the "On normal completion: 0" message always get printed or only print it when --verbose is specified?

**Comment by scandox** [comment]
Printed output, apart from cameras, only with verbose. Thanks

**Comment by scandox** [comment]
Reading over your email I suspect you may have misunderstood my original.
I don't need a printed message at all. I need an exit code passed to the
OS.

As

http://steve-parker.org/sh/exitcodes.shtml

Printed output, apart from cameras, only with verbose. Thanks

**Comment by liutingdu** [comment]
I've made it exit with exit code 1/0 for failure/success by using 
```java
System.exit(1/0)
```
And when I run ```echo $?```, it shows the exit code result. Is it what you are talking about? 

I was just wondering do you need it to be printed as a logging message or not :) So the answer is no?

**Comment by scandox** [comment]
Oh sorry ok great. No logging needed as the exit code tells the story
