### ISSUE TITLE
Sometimes after onVif discovery the runnable version doesn't return results

### ISSUE THREAD

**Issue by scandox** [evercam/evercam-discovery-java#9]
On average every second run, the runnable version hangs after the onVif discovery and does not output the list of discovered cameras.

**Comment by liutingdu** [comment]
Thanks @scandox, actually I haven't tested ONVIF because there was no ONVIF camera in my network, I'll check this :)

**Comment by scandox** [comment]
Oh! My camera is just hikvision cube.I think. Perhaps I misunderstood
results?

**Comment by liutingdu** [comment]
We don't have Hikvision cameras online in the office at this moment.. Haha don't worry, I'll get one online and test it!

**Comment by liutingdu** [comment]
Hi Dan,

I tried many times but still couldn't reproduce this. It always returns me the scanning results.

Did it hangs after you see the very long ONVIF response message?

The only way I can think of to debug this is to add more logs. Is it possible for me to have SSH access to your machine? Or you can try my next version later with more logs?

**Comment by scandox** [comment]
What happens if parsing Xml fails in some way? Would that cause no response?

**Comment by liutingdu** [comment]
I think if exception happens during parsing XML, it should finish the ONVIF discovery and return results from other discovery methods. There are many other possibilities because it's running all discovery methods in parallel, and I disabled some error logs in this version.

I can try make some improvements on possible places see if it solves the problem?

**Comment by scandox** [comment]
The point I am making is that since the program does not terminate then if
no error message is logged for parsing XML then I would not know if the
program was hanging or just ended.

Now why it would fail to parse one time and succeed another time with the
same camera I don't know...

Daniel
